### ISSUE TITLE
Add user authentication and password encryption

### ISSUE THREAD

**Issue by Joboa** [Joboa/expense-manager-app#2]
It seems raw passwords are saved in the database of which is not a good practice. Please check out for bcrypt package. It is used for password encryption. With regards to the user authentication, use json web token.

**Comment by sidiousvic** [comment]
Good! ✅ Rememebr to reference this issue when you close it via a commit. You can reference it with the hash `#`.

**Comment by Joboa** [comment]
Well noted

**Comment by Joboa** [comment]
I have added user authentication and password encryption based on #2
